wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.13.0
    cli_version: 0.19.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1745829295
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 14
      - 16
      - 23
      - 37
      4: 3.13.0
      5: 0.19.10
      8:
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.0007944310276574922
num_residual_blocks:
  desc: null
  value: 8
residual_scaling:
  desc: null
  value: 0.2
epochs:
  desc: null
  value: 100
